version: '2'
services:

  db:
    image: postgres:9.4.5
    environment:
      POSTGRES_DB: postgres # databases will be created separately
      POSTGRES_USER: app
      POSTGRES_PASSWORD: development-only
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      TZ: UTC
    ports:
      - ${DB_HOST_PORT}:5432
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d